### PR TITLE
Support VPC flow logs

### PR DESCRIPTION
**Pull request by drobinson123**
This allows a user to specify that the cloudwatch logs contain VPC flow log records. It adds structure to the flow logs so they can be easily searched.

### CODE REVIEW

**Comment by kkentzo** [comment]
@drobinson123 thanks for your contribution. I will check within the next few days and post back here.

**Comment by eirc** [comment]
@drobinson123 you think it makes sense to also provide an index template for the mapping types that are needed for the generated data? I'm not sure though how and where these are setup on a beat. These are the instructions for its use on metricbeat for example: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html

**Comment by drobinson123** [comment]
Yeah, that makes sense. I'll add them.

**Comment by edperry** [comment]
Any progress on this, I think this is exactly what I need. I am getting flow-logs and they are in a less then desirable format

**Pull request closed without merging**
